# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64caed6afcb606e5dbc476efb21ffc70d4f4c37b23824c3f4d1e6086abfac1c7dee3bca446ffb2fc90c878f60e612290818cf9abf171629cabb00be8a980d05a

test:
  secret_key_base: 24915e603f5c08abb9de92befa9292fdafa637254795a0696aaeab9e9ded5beef8ef911d31f05d5ca9fd6f30890ff6598619482fa91d88f142c5c75ceef07185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
